name: Backend CI/CD

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "gateway/**"
      - "chat-service/**"
      - "ai-service/**"

permissions:
  contents: read
  id-token: write

env:
  SERVICES: '["gateway","chat-service","ai-service"]'

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(env.SERVICES) }}

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Verify Azure Login
        run: |
          az account show
          az acr show --name ${{ secrets.ACR_NAME }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:${{ github.sha }} \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:latest \
            .

      - name: Show Docker Images
        run: docker images

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ matrix.service }}:latest